### ISSUE TITLE
Add more content to the basic CRUD tutorial

### ISSUE THREAD

**Issue by fang0rnz** [dwws-ufes/jbutler-base-project#4]
When using JButler, some bugs and hassles could be avoided simply by knowing some more of the project's architecture:

1- The architecture must be respected at all times, at the cost of any CRUD functionality not working if it's not, application, controller, persistence, domain and view must be inside a core package. (e.g. {...}.core.controller).
In WebContent, CRUD views must match the following pattern: /WebContent/core/manage{#Entities}/form.xhtml and /WebContent/core/manage{#Entities}/list.xhtm. If this is not followed, it simply will not work. There's also the possibility of overriding the default path, but I guess it is easier just to follow the standards (resistance is futile!).
e.g. folder WebContent/core/manageEntities with form.xhtml and list.xhtml in it. -> Named after {...}.core.controller.ManageEntityController and {...}.core.domain.Entity domain. 

2 - There must be a messages.properties in the package view inside the package core. At the cost of NullPointerException when trying to update a registered object in the database.

3 - The default template must be used otherwise you must refactor all of it's CSS and decorators since it's based on AdminLTE + Bootstrap Marvin model. Not forgetting to follow the **standards**, with all of JButler's base project decorators and css and stuff into WebContent/resources/default

**Comment by vitorsouza** [comment]
The tutorial was changed in part 4 to include information on the naming conventions followed by JButler when we implement CRUD features: https://github.com/dwws-ufes/jbutler/wiki/Tutorial%3A-a-Java-EE-Web-Profile-application-with-JButler%2C-part-4

Can you read it and see if this satisfies your issue? I'm closing it now, but you can reopen it if you have further comments/requests. 

Thanks!
